name: "CI for burger"

on: [push]

jobs:
  cooking:
    runs-on: ubuntu-latest
    steps:
      - name: Достать булочку
        run: |
          echo "Жарю котлету 5 минут"

      - name: Пожарить котлету
        run: |
          echo "Жарю котлету 5 минут"

      - name: Собрать бургер
        run: |
          echo "Собираю бургер: булочка + котлета + сыр"

  sale:
    runs-on: ubuntu-latest
    steps:
        - name: Отправить на кассу
          run: |
            echo "Отправить на кассу"

        - name: Выдать бургер клиенту
          run: |
            echo "Выдать бургер клиенту"

        - name: Получить оплату
          run: |
            echo "Получить оплату"
